### ISSUE TITLE
Add support for Byte encoder

### ISSUE THREAD

**Issue by ruudk** [ruudk/golang-pdf417#1]
https://github.com/ihabunek/pdf417-php/blob/develop/src/Encoders/ByteEncoder.php

**Comment by RMoerbe** [comment]
Now I need the ByteEncoder for german text like "öüä", is it possible for you to implement?
my code in Xbase++ is:

//-- BC -------------------------------------------------------- BC ------

/********************************************************************
        Name : byteCompaction
        Does : Codworterzeugung fuer BC
  Parameters : cString
     Returns :
       Notes : Der Byte Compaction (BC) Mode erlaubt die
               Verschluesselung von 256 internationalen Zeichen,
               inkl. der ASCII-Werte 0-127.
               Im BC-Mode werden 6 Zeichen in 5 PDF417-Codewords
               unter Verwendung des "Basis 256 zu Basis 900
               Konvertierungs-Algorithmus" codiert
********************************************************************/
FUNCTION byteCompaction(cString, iStart, iLength)
    MEMVAR aCodeWords, iCWPtr
    //** DEC VAR
    LOCAL k, j
    LOCAL iSize := (iLength / 6) * 5 + (iLength % 6)

    if (iSize + iCWPtr > MAX_DATA_CODEWORDS)
        Msgbox("The text is too big.","PDF417 - byteCompaction")
    endif

    iLength += iStart
    FOR k = iStart TO iLength STEP 6
        iif( (iLength - k < 44),iSize := iLength - k ,iSize := 6 )
        if (iSize < 5)
            FOR j = 1 TO iSize
                aCodeWords[iCWPtr++] := Asc( cString[k + j] )
            NEXT
        else
            byteCompaction6(cString, k)
        endif
    NEXT
RETURN NIL
/********************************************************************
        Name : byteCompaction6
        Does : Codworterzeugung fuer BC in 6er Bloecken
  Parameters :
     Returns :
       Notes :  Kodierung der BC-Zeichen b5...b0 {231,101,11,97,205,2}
                Berechnung der Summe t aus den dezimalen Werten der 6 Zeichen:
                t = 231*2565+101*2564+11*2563+97*2562+205*2561+2*2560
                  = 254421168672002
                Berechnung des Codesworts 0
                 d0 = 254421168672002 mod 900 = 302
                 t = 254421168672002 div 900 = 282690187413
                Berechnung des Codesworts 1
                 d1 = 282690187413 mod 900 = 213
                 t = 282690187413 div 900 = 314100208
                Berechnung des Codesworts 2
                 d2 = 314100208 mod 900 = 208
                 t = 314100208 div 900 = 349000
                Berechnung des Codesworts 3
                 d3 = 349000 mod 900 = 700
                 t = 349000 div 900 = 387
                Berechnung des Codesworts 4
                 d4 = 387 mod 900 = 387
                 t = 387 div 900 = 0
                Die Codewort Sequenz d4 ... d0 ist 387,700,208,213,302
********************************************************************/
FUNCTION byteCompaction6(cString, iStart)
    MEMVAR aCodeWords, iCWPtr
    //** DEC VAR
    LOCAL iLength   := 6
    LOCAL iRet      := iCWPtr
    LOCAL iRetLast  := 4
    LOCAL ni, k;

    iCWPtr += iRetLast + 1
    FOR k = 0 TO iRetLast//+1
        aCodeWords[iRet+k] := 0
    NEXT
    iLength += iStart

    FOR ni = iStart TO iLength-1

        // multiply by 256
        FOR k = iRetLast TO 0 STEP -1
            aCodeWords[iRet+k] := aCodeWords[iRet+k] * 256
        NEXT

        // add the digit
        aCodeWords[iRet + iRetLast] += Asc( cString[ni+1] )

        // propagate carry
        FOR k = iRetLast TO 1 STEP -1
            aCodeWords[iRet+k - 1] += Int(aCodeWords[iRet+k] / 900)
            aCodeWords[iRet+k] %= 900
        NEXT
    NEXT
RETURN NIL
//-- BC -------------------------------------------------------- BC ------

best regards
RM
