### ISSUE TITLE
How to use this lib

### ISSUE THREAD

**Issue by mpapec** [ruudk/golang-pdf417#2]
Is there some docs/gist on how to use this lib? I'm not familiar with golang. tnx

**Comment by ruudk** [comment]
I made it to be used inside https://github.com/jung-kurt/gofpdf in combination with https://github.com/boombuler/barcode

**Comment by ruudk** [comment]
Updated readme with added example: https://github.com/ruudk/golang-pdf417/blob/master/README.md
