### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by nicolasStevenin** [ruudk/golang-pdf417#6]
Hi !
When I try to test your project, i have this issue :   

**command: go test -buildmode pie -compiler gc -ldflags "-X github.com/ruudk/golang-pdf417/version.commit=36fb797433a6abf172ad7a6d5eaaf55d7cea4b7b -X github.com/ruudk/golang-pdf417/version=0 -extldflags '-Wl,-z,relro  '"**
   testing: github.com/ruudk/golang-pdf417
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55c73c4bdf4f]

Thanks

**Comment by ruudk** [comment]
Sorry, I must have missed this issue long time ago. 

If it's still relevant, please re-open so we can fix it.
